// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brand-kit/BrandGuidelines.tsx": () => import("../components/mockups/brand-kit/BrandGuidelines.tsx"),
  "./components/mockups/brand-kit/BrandInAction.tsx": () => import("../components/mockups/brand-kit/BrandInAction.tsx"),
  "./components/mockups/brand-kit/ColorTypography.tsx": () => import("../components/mockups/brand-kit/ColorTypography.tsx"),
  "./components/mockups/brand-kit/LogoConcepts.tsx": () => import("../components/mockups/brand-kit/LogoConcepts.tsx")
};
